platform:ios,'8.0'

target 'MHRefresh' do

pod 'MLeaksFinder'
pod 'AFNetworking'
pod 'MJRefresh'
pod 'MBProgressHUD'
pod 'IQKeyboardManager'
pod 'SVProgressHUD'
pod 'YYKit'
pod 'YTKNetwork'
pod 'RESideMenu','~> 4.0.7'
pod 'ReactiveCocoa','~> 7.0'
pod 'PNChart'


source 'https://github.com/CocoaPods/Specs.git'
pod 'libPhoneNumber-iOS', '~> 0.8'

end
