platform:ios,'8.0'

target 'MHRefresh' do

pod 'MLeaksFinder'
pod 'AFNetworking'
pod 'MJRefresh'
pod 'MBProgressHUD'
pod 'IQKeyboardManager'
pod 'SVProgressHUD'

source 'https://github.com/CocoaPods/Specs.git'
pod 'libPhoneNumber-iOS', '~> 0.8'

end
